os: linux
dist: xenial
language: python

git:
  depth: false

env:
  - PRE_COMMIT_HOME=$HOME/.cache/pre-commit

virtualenv:
  system_site_packages: false

jobs:
  fast_finish: true
  include:
    - stage: "Tests"
    - name: "Python 3.10"
      python: 3.8
      env: DISTRIB="ubuntu" TOXENV="py310" COVERAGE="true" TEST="true"
    - stage: "Deploy"
      name: "Deploy to Github pages"
      env: COVERAGE="false" TEST="false" DEPLOY="true"
      deploy:
        provider: pages
        keep_history: true
        local_dir: site
        strategy: git
        edge: true
        on:
          branch: feature/docs


install:
  - pip install pip-tools
  - pip-sync
  - pip install coveralls

before_script:
  - pip list
  - which tox

script:
  - |
    if [[ "$TEST" == "true" ]]; then
      make test-ci
    fi
  - |
    if [[ "$COVERAGE" == "true" ]]; then
      pre-commit install
      pre-commit run --all-files
    fi
  - |
    if [[ "$DEPLOY" == "true" ]]; then
      mkdocs build
    fi

after_success:
  - if [[ "$COVERAGE" == "true" ]]; then coveralls || echo "failed"; fi

cache:
  pip: true
  directories:
    - $HOME/.cache/pre-commit
