language: python
git:
  depth: false
env:
  - PRE_COMMIT_HOME=$HOME/.cache/pre-commit

virtualenv:
  system_site_packages: false

jobs:
  fast_finish: true
  include:
    - stage: "Tests"
      name: "Python 3.6"
      python: 3.6
      env: DISTRIB="ubuntu" TOXENV="py36" COVERAGE="false"
    - name: "Python 3.7"
      python: 3.7
      env: DISTRIB="ubuntu" TOXENV="py37" COVERAGE="false"
    - name: "Python 3.8"
      python: 3.8
      env: DISTRIB="ubuntu" TOXENV="py38" COVERAGE="true"
    - stage: "Deploy"


install:
  - pip install pip-tools
  - pip-sync
  - pip install coveralls

before_script:
  - pip list
  - which tox

script:
  - make test-ci
  - |
    if [[ "$COVERAGE" == "true" ]]; then
      pre-commit install
      pre-commit run --all-files
    fi
  - mkdocs build

after_success:
  - if [[ "$COVERAGE" == "true" ]]; then coveralls || echo "failed"; fi

after_script:
  - travis-cleanup

deploy:
  provider: pages
  skip_cleanup: true
  github_token: $GH_TOKEN
  keep_history: true
  local_dir: site
  strategy: git
  on:
    branch: feature/docs

cache:
  pip: true
  directories:
    - $HOME/.cache/pre-commit
